name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.16.0]

    steps:
      - run: sudo chown -R $USER:$USER /etc/action-runner/
      - run: sudo chmod -R 755 /etc/action-runner/
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd /etc/action-runner/jericmontana/_work/me/me/server && sudo yarn
      - run: sudo systemctl restart nginx
      